name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    uses: sxzz/workflows/.github/workflows/release.yml@next
    with:
      publish: true
    permissions:
      contents: write
      id-token: write

  # release-jsr:
  #   uses: sxzz/workflows/.github/workflows/release-jsr.yml@next
  #   permissions:
  #     contents: read
  #     id-token: write
