name: Setup JavaScript
description: Setup JavaScript environment

inputs:
  persist-credentials:
    description: Whether to configure the token or SSH key with the local git config
    default: 'false'

  fetch-all:
    description: Whether to fetch all history for all branches and tags.
    default: 'false'

  node-version:
    description: 'Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.'
    default: 'lts/*'

  auto-install:
    description: Whether to automatically install dependencies.
    default: 'true'

  package-manager:
    description: 'Package manager to use. Examples: npm, yarn, pnpm.'
    default: pnpm

  no-frozen-lockfile:
    description: Whether to disable frozen lockfile installation.
    default: 'false'

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        persist-credentials: ${{ inputs.persist-credentials }}
        fetch-depth: "${{ inputs.fetch-all == 'true' && '0' || '1' }}"

    - name: Install pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      if: ${{ inputs.package-manager == 'pnpm' }}

    - name: Setup node
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.package-manager }}
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      shell: bash
      run: ${{ inputs.package-manager }} install ${{ inputs.no-frozen-lockfile == 'true' && '--no-frozen-lockfile' || '' }}
      if: ${{ inputs.auto-install }}
