name: Setup JavaScript
description: Setup JavaScript environment

inputs:
  persist-credentials:
    description: Whether to configure the token or SSH key with the local git config
    default: false

  fetch-all:
    description: Whether to fetch all history for all branches and tags.
    default: false

  node-version:
    description: 'Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.'
    default: 'lts/*'

  auto-install:
    description: Whether to automatically install dependencies.
    default: true

  package-manager:
    description: 'Package manager to use. Examples: npm, yarn, pnpm.'
    default: pnpm

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: ${{ inputs.persist-credentials }}
        fetch-depth: "${{ inputs.fetch-all == 'true' && '0' || '1' }}"

    - name: Install pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

    - name: Setup node
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.package-manager }}
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      shell: bash
      run: ${{ inputs.package-manager }} install
      if: ${{ inputs.auto-install }}
