name: Coverage

on:
  workflow_call:
    inputs:
      test:
        required: false
        type: string
        default: pnpm run test --coverage

      build:
        required: false
        type: string
        default: pnpm run build

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Setup JS
        uses: sxzz/workflows/setup-js@v2

      - name: Build
        run: ${{ inputs.build }}

      - name: Coverage
        run: ${{ inputs.test }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad # v5.5.3
        with:
          use_oidc: true
