name: Coverage

on:
  workflow_call:
    inputs:
      test:
        required: false
        type: string
        default: pnpm run test --coverage

      build:
        required: false
        type: string
        default: pnpm run build

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Setup JS
        uses: sxzz/workflows/setup-js@v2

      - name: Build
        run: ${{ inputs.build }}

      - name: Coverage
        run: ${{ inputs.test }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          use_oidc: true
