name: Release Pre-release
on:
  workflow_call:
    inputs:
      build:
        required: false
        type: string
        default: pnpm run build
      compact:
        required: false
        type: boolean
        default: false
      packages:
        required: false
        type: string
        default: ''

jobs:
  publish:
    name: Publish Pre-release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: ${{ inputs.build }}

      - name: Publish prerelease
        run: pnpm dlx pkg-pr-new@0.0 publish --pnpm ${{ inputs.compact && '--compact' || '' }} ${{ inputs.packages }}
