name: Release JSR

on:
  workflow_call:
    inputs:
      build:
        required: false
        type: string
        default: ''

jobs:
  release-jsr:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: ${{ inputs.build }}
        if: ${{ inputs.build }}

      - name: Publish to JSR
        run: pnpx jsr publish
