name: Unit Test Dogfooding

on:
  push:
    branches: [main, next]
  pull_request:
    branches: [main, next]

permissions: {}

jobs:
  unit-test:
    uses: sxzz/workflows/.github/workflows/unit-test.yml@next
